// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2tT6zKfVCErjb7S6Yo_gmSk0rbEPR7TM',
    appId: '1:775271281144:web:YOUR_WEB_APP_ID',
    messagingSenderId: '775271281144',
    projectId: 'kairoai-041828',
    authDomain: 'kairoai-041828.firebaseapp.com',
    storageBucket: 'kairoai-041828.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2tT6zKfVCErjb7S6Yo_gmSk0rbEPR7TM',
    appId: '1:775271281144:android:e3d85114d3f8cfe7e1a60d',
    messagingSenderId: '775271281144',
    projectId: 'kairoai-041828',
    storageBucket: 'kairoai-041828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2tT6zKfVCErjb7S6Yo_gmSk0rbEPR7TM',
    appId: '1:775271281144:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '775271281144',
    projectId: 'kairoai-041828',
    storageBucket: 'kairoai-041828.firebasestorage.app',
    iosBundleId: 'com.kairo.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2tT6zKfVCErjb7S6Yo_gmSk0rbEPR7TM',
    appId: '1:775271281144:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '775271281144',
    projectId: 'kairoai-041828',
    storageBucket: 'kairoai-041828.firebasestorage.app',
    iosBundleId: 'com.kairo.ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2tT6zKfVCErjb7S6Yo_gmSk0rbEPR7TM',
    appId: '1:775271281144:web:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '775271281144',
    projectId: 'kairoai-041828',
    authDomain: 'kairoai-041828.firebaseapp.com',
    storageBucket: 'kairoai-041828.firebasestorage.app',
  );
}
