// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYLK75UJ1cN12CC_x6hICGDkIm6khPC4s',
    appId: '1:15850903584:web:YOUR_WEB_APP_ID',
    messagingSenderId: '15850903584',
    projectId: 'kairo-ai-041828',
    authDomain: 'kairo-ai-041828.firebaseapp.com',
    storageBucket: 'kairo-ai-041828.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYLK75UJ1cN12CC_x6hICGDkIm6khPC4s',
    appId: '1:15850903584:android:6aaf804ebb28d65b234445',
    messagingSenderId: '15850903584',
    projectId: 'kairo-ai-041828',
    storageBucket: 'kairo-ai-041828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLK75UJ1cN12CC_x6hICGDkIm6khPC4s',
    appId: '1:15850903584:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '15850903584',
    projectId: 'kairo-ai-041828',
    storageBucket: 'kairo-ai-041828.firebasestorage.app',
    iosBundleId: 'com.kairo.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYLK75UJ1cN12CC_x6hICGDkIm6khPC4s',
    appId: '1:15850903584:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '15850903584',
    projectId: 'kairo-ai-041828',
    storageBucket: 'kairo-ai-041828.firebasestorage.app',
    iosBundleId: 'com.kairo.ai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYLK75UJ1cN12CC_x6hICGDkIm6khPC4s',
    appId: '1:15850903584:web:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '15850903584',
    projectId: 'kairo-ai-041828',
    authDomain: 'kairo-ai-041828.firebaseapp.com',
    storageBucket: 'kairo-ai-041828.firebasestorage.app',
  );
}
